name: Security - Dependency Check

on:
  workflow_call:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4

    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: '{{ cookiecutter.service_slug }}'
        path: '.'
        format: 'ALL'
        args: >
          --enableRetired
          --enableExperimental
          --suppressionFile .github/dependency-check-suppressions.xml
        failOnCVSS: 7

    - name: Upload Test results
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: reports/
        retention-days: 30

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: reports/dependency-check-report.sarif

  container-scan:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    permissions:
      contents: read
      security-events: write
      packages: read

    steps:
    - uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/equilibretech/projects-{{ cookiecutter.service_slug }}:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        
    - name: Upload Trivy scan results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

  license-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check licenses
      uses: fossa-contrib/fossa-action@v2
      continue-on-error: true
      with:
        api-key: ${{ secrets.FOSSA_API_KEY }}
        
    - name: License Finder
      uses: github/licensed-ci@v1
      continue-on-error: true
      with:
        config_file: .github/licensed.yml